I2cCtrlReadError: Read errors from RelaisController because SystemController support is not yet ready
Signed-off-by: i-sundermann <i.sundermann@zera.de>